# ===============================
# CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=backend
server.port=8080

# ===============================
# MYSQL / DATASOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/sistemacitasodontologicas?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hibernate detecta el dialecto automáticamente en Spring Boot 3, pero se mantiene por consistencia
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SECURITY / JWT
# ===============================
# Secreto codificado en Base64 (HS256)
jwt.secret=bWlDbGF2ZVN1cGVyU2VjcmV0YVBhcmFTaXN0ZW1hQ2l0YXNPZG9udG9sb2dpY2FzMjAyNg==
# Expiración: 24 horas (en milisegundos)
jwt.expiration=86400000

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# CONFIGURACIÓN DE PASARELAS DE PAGO
# ===============================

# PAYPAL
paypal.client.id=AUTga9HneLY49lx5K5c5i7PYP9ZvhL0haAB2wnS0dxgfzL11RpB0DaklvouR7_GlsO7z01U5EQINZy9h
paypal.client.secret=EMOePwl67yF80UsaytgyTA-25cpFUxD8wUYvMNPTxJbVmv2Iq_xPgffS5IMnugeY08S525jPLVFbhPBZ
paypal.mode=sandbox

# ===============================
# EMAIL CONFIG
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=odontonovasistema@gmail.com
spring.mail.password=ylnnncknqlgwmoyn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

