
spring.application.name=backend
server.port=8080

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/sistemacitasodontologicas?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=bWlDbGF2ZVN1cGVyU2VjcmV0YVBhcmFTaXN0ZW1hQ2l0YXNPZG9udG9sb2dpY2FzMjAyNg==
jwt.expiration=86400000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

paypal.client.id=AUTga9HneLY49lx5K5c5i7PYP9ZvhL0haAB2wnS0dxgfzL11RpB0DaklvouR7_GlsO7z01U5EQINZy9h
paypal.client.secret=EMOePwl67yF80UsaytgyTA-25cpFUxD8wUYvMNPTxJbVmv2Iq_xPgffS5IMnugeY08S525jPLVFbhPBZ
paypal.mode=sandbox

sendgrid.api.key=${SENDGRID_API_KEY}
